  motion_az_on:
    alias: "Turn on lamp and set timer"
    sequence:
      # Cancel ev. old timers
      - service: script.turn_off
        data:
           entity_id: script.motion_az_off
      - service: light.turn_on
        data:
          entity_id: light.schreibtisch_christian
      # Set new timer
      - service: script.turn_on
        data:
          entity_id: script.motion_az_off

  motion_az_off:
    alias: "Turn off lamp after 5 minutes"
    sequence:
      - delay:
          minutes: 5
      - service: light.turn_off
        data:
          entity_id: light.schreibtisch_christian