- alias: Kellerbeleuchtung ein
  hide_entity: True
  trigger:
    platform: state
    entity_id: binary_sensor.kellertuer_sensor
    to: 'on'
  action:
    service: light.turn_on
    entity_id:
      - light.keller
      - light.kellertreppe

- alias: Kellerbeleuchtung aus
  hide_entity: True
  trigger:
    platform: state
    entity_id: binary_sensor.kellertuer_sensor
    to: 'off'
  action:
    service: light.turn_off
    entity_id:
      - light.keller
      - light.kellertreppe