- alias: "Media player paused/stopped"
  trigger:
    platform: state
    entity_id: media_player.atv_wohnzimmer
    to: 'idle'
  condition:
    condition: sun
    after: sunset
  action:
    - service: light.turn_on
      entity_id:
        - light.couch
        - light.bodenlampe
      data:
        brightness: 150
        rgb_color: [255, 255, 255]

- alias: "Media player playing"
  trigger:
    - platform: state
      entity_id: media_player.atv_wohnhzimmer
      to: 'playing'
  condition:
    - condition: sun
      after: sunset
  action:
    - service: light.turn_off
      entity_id:
        - light.decke
        - light.bodenlampe
    - service: light.turn_on
      entity_id:
        - light.couch
      data:
        brightness: 20
        rgb_color: [0, 255, 0]