- alias: Beleuchtung bei Sonnenuntergang normal
  trigger:
    platform: sun
    event: sunset
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.all_devices
        state: 'home'
      - condition: state
        entity_id: input_boolean.summermode
        state: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.Abendbeleuchtung

- alias: Beleuchtung bei Sonnenuntergang Sommermodus
  trigger:
    platform: sun
    event: sunset
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.all_devices
        state: 'home'
      - condition: state
        entity_id: input_boolean.summermode
        state: 'on'
      - condition: state
        entity_id: binary_sensor.wohnzimmer_schiebetuer_sensor
        state: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.Sommerbeleuchtung