############################################################################
#
# Away
#
############################################################################

- alias: Turn light of at away
  trigger:
    platform: state
    entity_id: group.all_devices
    from: 'home'
    to: 'not_home'
  action:
    service: homeassistant.turn_off
    entity_id: group.all_lights


############################################################################
#
# Arrive
#
############################################################################

- alias: Turn lights on
  trigger:
    platform: state
    entity_id: group.all_devices
    from: 'not_home'
    to: 'home'
  condition:
    condition: sun
    after: sunset
  action:
    - service: homeassistant.turn_on
      entity_id:
        - light.bodenlampe
        - light.couch
      data:
        brightness: 150
        rgb_color: [ 255, 255, 255 ]