  - platform: template
    sensors: 
      nextsunrise:
        friendly_name: "Sonnenaufgang"
        value_template: "{{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom('%-H:%M') }}"
        icon_template: mdi:weather-sunset-up

      nextsunset:
        friendly_name: "Sonnenuntergang"
        value_template: "{{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom('%-H:%M') }}"
        icon_template: mdi:weather-sunset-down