- alias: Restart Home-Assistant after Traivs CI Build
  trigger:
    - platform: state
      entity_id: sensor.cbirkenbeulhomeassistant_last_build_state
      from: 'started'
      to: 'passed'
  action:
    - service: shell_command.git_pull
    - delay: '00:00:10'
    - service: shell_command.restart_hass