  - alias: 'Resync Voice controll'
    trigger:
      - platform: event
        event_type: zwave.network_ready
    action:
      - service: homekit.start
      - service: google_assistant.request_sync