############################################################################
#
# Luftfeuchtigkeit
#
############################################################################

 sensor.wohnzimmer_relative_humidity:
  icon: mdi:water-percent
  friendly_name: Luftfeuchtigkeit Wohnzimmer
  homebridge_name: Luftfeuchtigkeit Wohnzimmer