############################################################################
#
# Temperaturen
#
############################################################################

 sensor.motion_arbeitszimmer_temperature:
  icon: mdi:thermometer

 sensor.flur_temperatur:
  icon: mdi:thermometer
  friendly_name: Temperatur Flur

 climate.heizung_badezimmer_heating_1:
  icon: mdi:thermometer
  friendly_name: Heizung Badezimmer

 climate.heizung_az_christian_heat:
  icon: mdi:thermometer
  friendly_name: Heizung Christian

 sensor.wohnzimmer_temperature:
  icon: mdi:thermometer
  friendly_name: Temperatur Wohnzimmer