############################################################################
#
# Temperaturen
#
############################################################################

 sensor.motion_arbeitszimmer_temperature:
  icon: mdi:thermometer

 sensor.flur_temperatur:
  icon: mdi:thermometer
  friendly_name: Flur Temperatur

 climate.heizung_badezimmer_heating_1:
  icon: mdi:thermometer
  friendly_name: Badezimmer Heizung

 sensor.heizung_badezimmer_temperature:

 climate.heizung_az_christian_heat:
  icon: mdi:thermometer
  friendly_name: Heizung Christian

 sensor.wohnzimmer_temperature:
  icon: mdi:thermometer
  friendly_name: Temperatur