############################################################################
# Global
############################################################################

homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: Europe/Berlin
  customize: !include_dir_merge_named customizations/

sun:

############################################################################
# Configuration Splitting
############################################################################

automation: !include_dir_merge_list automations/
#input_select: !include_dir_merge_named input_select/
#input_number: !include_dir_merge_named input_number/
input_boolean: !include  input-boolean.yaml
scene: !include_dir_merge_list scenes/
script: !include_dir_merge_named scripts/
sensor: !include_dir_merge_list sensors/
switch: !include_dir_merge_list switches/
group: !include groups.yaml

############################################################################
# Frontend & Addons
############################################################################

frontend:

http:
  api_password: !secret http_password
  base_url: !secret http_url

config:

############################################################################
# History & Data collecting
############################################################################

recorder:
  purge_interval: 2
  purge_keep_days: 5
  db_url: !secret recorder_url

mqtt:
  broker: !secret mqtt_server

############################################################################
# Hardware
############################################################################

hue:
  bridges:
    - host: !secret hue_ip
      allow_hue_groups: false

zwave:
  usb_path: /dev/ttyACM0

vacuum:
  - platform: xiaomi_miio
    host: 192.168.2.247
    token: !secret xmi_token

device_tracker:
  - platform: unifi
    host: !secret unifi_host
    port: !secret unifi_port
    username: !secret unifi_user
    password: !secret unifi_password
    verify_ssl: False
    new_device_defaults:
      track_new_devices: false
      hide_if_away: false

climate:
  - platform: zwave

############################################################################
# MediaPlayer
############################################################################

media_player:
  - platform: plex
    entity_namespace: 'plex'

sonos:
  media_player:
    hosts: 192.168.2.244

apple_tv:
  host: 192.168.2.245
  login_id: 00000000-0a42-b2cc-516d-7747d33442b0
  name: ATV_Wohnzimmer
  start_off: true
  credentials: 0702CD162BF7D9A6:7467E58FEFF280F86EA1F9D85BC9CA50EAED7B6865033971D91BFF34C6F461E1

############################################################################
# HomeKit
############################################################################

homekit:
  auto_start: false
  filter:
    include_domains:
      - light
      - input_boolean
      - switch
      - climate
    exclude_domains:
      - script
      - automations
      - sensor

############################################################################
# Google Assistant
############################################################################

google_assistant:
  project_id: home-assistant-6c013
  client_id: !secret ga_clientid
  access_token: !secret ga_accesstoken
  agent_user_id: !secret ga_agentuserid
  api_key: !secret ga_apikey
  exposed_domains:
    - switch
    - light
    - scene
    - input_boolean
  entity_config:
    scene.Abendbeleuchtung:
      room: Wohnzimmer
    light.bad:
      expose: False
    light.Bloom:
      room: Arbeitszimmer
    light.Bodenlampe:
      room: Wohnzimmer
    light.couch:
      room: Wohnzimmer
    light.Decke:
      room: Wohnzimmer
    switch.steckdose_gummibaum_switch:
      room: Wohnzimmer
    switch.steckdose_katzenbrunnen_switch:
      room: Wohnzimmer
    light.Kellertreppe:
      expose: False
    light.Kellervorraum:
      expose: False
    light.Medizinschrank:
      expose: False
    light.Schreibtisch_Christian:
      room: Arbeitszimmer
    light.Schreibtisch_Petra:
      room: Arbeitszimmer
    input_boolean.evening_lightning_default:
      expose: False
    input_boolean.nightmode:
      name: Gute Nacht

  

############################################################################
# Notifications
############################################################################

ios:

notify:
  - name: iosgroup
    platform: group
    services:
      - service: !secret iphone1
      - service: !secret iphone2

############################################################################
# Shell Commands
############################################################################

shell_command:
  restart_hass: 'systemctl restart home-assistant'
  git_pull: 'bash /root/git-pull.sh'

############################################################################
# Alerts
############################################################################

alert:
  bathroom_window:
    name: Badezimmerfenster offen
    done_message: Badezimmerfenster geschlossen
    entity_id: binary_sensor.badezimmer_sensor
    state: 'on'
    repeat: 5
    can_acknowledge: True
    skip_first: True
    notifiers:
      - iosgroup

  bathroom_window:
    name: Kellterür offen
    done_message: Kellertür geschlossen
    entity_id: binary_sensor.kellertuer_sensor
    state: 'on'
    repeat: 5
    can_acknowledge: True
    skip_first: True
    notifiers:
      - iosgroup