############################################################################
# Global
############################################################################

homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: Europe/Berlin
  customize: !include_dir_merge_named customizations/

sun:

############################################################################
# Configuration Splitting
############################################################################

automation: !include_dir_merge_list automations/
#input_select: !include_dir_merge_named input_select/
#input_number: !include_dir_merge_named input_number/
input_boolean: !include  input-boolean.yaml
scene: !include_dir_merge_list scenes/
script: !include_dir_merge_named scripts/
sensor: !include_dir_merge_list sensors/
switch: !include_dir_merge_list switches/
group: !include groups.yaml

############################################################################
# Frontend & Addons
############################################################################

frontend:

http:
  api_password: !secret http_password
  base_url: !secret http_url

config:

############################################################################
# History & Data collecting
############################################################################

recorder:
  purge_interval: 2
  purge_keep_days: 5
  db_url: !secret recorder_url

############################################################################
# Hardware
############################################################################

hue:
  bridges:
    - host: !secret hue_ip
      allow_hue_groups: false

zwave:
  usb_path: /dev/ttyACM0

vacuum:
  - platform: xiaomi_miio
    host: 192.168.2.247
    token: !secret xmi_token

device_tracker:
  - platform: unifi
    host: !secret unifi_host
    port: !secret unifi_port
    username: !secret unifi_user
    password: !secret unifi_password
    verify_ssl: False
    new_device_defaults:
      track_new_devices: false
      hide_if_away: false

############################################################################
# HomeKit
############################################################################

homekit:
  auto_start: false
  filter:
    include_domains:
      - light
      - input_boolean
    exclude_domains:
      - script
      - sensor
      - automations

############################################################################
# Notifications
############################################################################

ios:

notify:
  - name: iosgroup
    platform: group
    services:
      - service: !secret iphone1
      - service: !secret iphone2

############################################################################
# Shell Commands
############################################################################

shell_command:
  restart_hass: 'systemctl restart home-assistant'
  git_pull: 'bash /root/git-pull.sh'