  default_view:
    view: yes
    icon: mdi:home-assistant
    entities:
      - group.weather
      - group.roomclimate
      - group.lights
      - group.household
      - group.switches
      - group.heating
      - group.system

  weather:
    name: Wetter & Umwelt
    entities:
      - sensor.nextsunset
      - sensor.nextsunrise
      - sensor.weewx_outtemp

  lights:
    name: Licht
    entities:
      - light.bloom
      - light.bodenlampe
      - light.couch
      - light.decke
      - light.schreibtisch_christian
      - light.schreibtisch_petra

  household:
    name: Haushalt
    entities:
      - device_tracker.petrasiphone6
      - device_tracker.teqqphone
      - vacuum.xiaomi_vacuum_cleaner

  switches:
    name: Steckdosen
    entities:
      - switch.steckdose_gummibaum_switch
      - switch.steckdose_katzenbrunnen_switch

  heating:
    name: Heizung
    entities: 
      - climate.heizung_az_christian_heat
      - climate.heizung_badezimmer_heating_1

  roomclimate:
    name: Raumklima
    entities:
      - sensor.wohnzimmer_relative_humidity
      - sensor.wohnzimmer_temperature
      - sensor.flur_temperatur

  system:
    name: System
    entities:
      - script.restart_hass
      - script.git_pull
      - sensor.cbirkenbeulhomeassistant_last_build_state