  evening_lightning_default:
    name: Abendbeleuchtung
    initial: off

  nightmode:
    name: Nachtmodus
    initial: off
    icon: mdi:weather-night

  summermode:
    name: Sommerzeit
    initial: off
    icon: mdi:weather-sunny