############################################################################
# Global
############################################################################

latitude: 49.172681265
longitude: 7.24719827
elevation: 244

github_key: blablabla

############################################################################
# Frontend & Addons
############################################################################

http_password: secret
http_url: home-assistant.io

############################################################################
# History & Data collecting
############################################################################

recorder_url: mysql://user:password@host/homeassistant

influx_host: 0.0.0.0
influx_db: homeassistant

############################################################################
# Hardware
############################################################################

hue_ip: 0.0.0.0

xmi_token: 685a57471176686e78509d664c680815

############################################################################
# Notifications
############################################################################

iphone1: iphone1
iphone2: iphone2