  bathroom_window:
    name: Badezimmerfenster offen
    done_message: Badezimmerfenster geschlossen
    entity_id: binary_sensor.badezimmer_sensor
    state: 'on'
    repeat: 5
    can_acknowlege: True
    skip_first: True
    notifiers:
      - iosgroup